# Generated by Django 2.2.1 on 2019-09-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='add_date',
            new_name='add_time',
        ),
    ]
