# Generated by Django 2.2.1 on 2019-09-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190928_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='node',
            field=models.ForeignKey(default=None, on_delete='models.CASCADE', to='api.Node'),
        ),
    ]
