# Generated by Django 2.2.1 on 2019-09-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='node',
        ),
    ]
