# Generated by Django 2.2.1 on 2019-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.AddField(
            model_name='project',
            name='node',
            field=models.ForeignKey(default=None, on_delete='models.CASCADE', to='api.Node'),
        ),
    ]
