# Generated by Django 2.2.1 on 2019-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190928_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
