# Generated by Django 2.1.7 on 2019-10-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190930_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='node',
            field=models.CharField(default='', max_length=128),
        ),
    ]
