# Generated by Django 2.2.1 on 2019-10-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_job_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='running',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Deploy',
        ),
    ]
