# Generated by Django 2.2.1 on 2019-10-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191012_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
