# Generated by Django 2.2.1 on 2019-09-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anything', '0002_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
