# Generated by Django 2.2.1 on 2019-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anything', '0003_delete_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPorfile',
        ),
    ]
